version: "3.9"

services:
  nodejs-app:
    container_name: nodejs_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pdf-view

    depends_on:
      - mongo

  mongo:
    container_name: mongo_container
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
